### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by waltcow** [yjcyxky/ossutil-github-action#1]
Fail to run job in macOS-latest version

**Comment by yjcyxky** [comment]
> Fail to run job in macOS-latest version

Sorry, because I don't need to test on macOS, so i did't consider to add support on it.

If you need it, maybe i can add this support in next few days.

Do you have any suggestion or documents on it? 

Thank you for your advice.

**Comment by waltcow** [comment]
Recently,  I start to use github action to build my project which is  based on Electron.

I need to build macos/windows installer in different platform and then upload the binary to my oss bucket.

If you  consider to add support on it.  I glad to help

**Comment by yjcyxky** [comment]
Yeah, i'm glad to add the support.

But I don't know how to build an action to support Windows, macOS and Linux.

I found the document: https://help.github.com/en/actions/building-actions/about-actions

I plan to learn it, and then try to fix the issue.

If you have the experience to support macOS & Windows, welcome to submit a Pull Request.

**Comment by yjcyxky** [comment]
In my opinion, if i want to support all os, i need to build action by using javascript, not docker.

right?

**Comment by waltcow** [comment]
I found the related issue https://github.community/t5/GitHub-Actions/Why-is-Docker-not-installed-on-macOS/td-p/39364

If your want to support all os,  javascript is the only option in current circumstance

**Comment by yjcyxky** [comment]
I built a javascript action for ossutil in https://github.com/go-choppy/ossutil-github-action-js

Maybe it can match your need.

Welcome you to try it in your project. If you have any questions, please submit an issue to the new repo

**Comment by waltcow** [comment]
I do the same thing today, hahhah,

thanks anyway

https://github.com/waltcow/ossutil-action
